package dev.cluvex.zedsecure.domain.config

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class WireguardConfHeaderTest {
    private val conf = """
        # Name = 198.51.100.7
        [Interface]
        PrivateKey = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
        Address = 10.13.13.2/32
        DNS = 1.1.1.1, 1.0.0.1
        Jc = 6
        Jmin = 10
        Jmax = 50
        I1 = <r 2><b 0x0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728>

        [Peer]
        PublicKey = BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=
        Endpoint = 192.0.2.10:13579
        AllowedIPs = 0.0.0.0/0
        PersistentKeepalive = 25
    """.trimIndent()

    @Test
    fun `a header comment no longer hides the config behind it`() {
        assertTrue("this is the file that was refused", ConfigParser.looksLikeWireguardConf(conf))

        assertTrue(ConfigParser.looksLikeWireguardConf("﻿\n\n$conf"))

        assertFalse(ConfigParser.looksLikeWireguardConf("""{"note":"[Interface] and [Peer] go in a .conf"}"""))
    }

    @Test
    fun `the profile is named by its header, not by its endpoint`() {
        assertEquals("198.51.100.7", ConfigParser.wireguardConfName(conf))
        assertEquals("198.51.100.7", ConfigParser.parseWireguardConf(conf).remark)

        val bare = conf.lines().drop(1).joinToString("\n")
        assertEquals("", ConfigParser.wireguardConfName(bare))
        assertEquals("192.0.2.10", ConfigParser.parseWireguardConf(bare).remark)
    }

    @Test
    fun `the other header spellings work too`() {
        assertEquals("Berlin", ConfigParser.wireguardConfName("# Name: Berlin\n[Interface]\n"))
        assertEquals("Berlin", ConfigParser.wireguardConfName("#name=Berlin\n[Interface]\n"))
        assertEquals("Berlin", ConfigParser.wireguardConfName("; Name = Berlin\n[Interface]\n"))

        assertEquals("", ConfigParser.wireguardConfName("# generated by the panel\n[Interface]\n"))
    }

    @Test
    fun `everything the file states reaches the parsed config`() {
        val c = ConfigParser.parseWireguardConf(conf)

        assertEquals(Protocol.AMNEZIAWG, c.protocol)
        assertEquals("192.0.2.10", c.address)
        assertEquals(13579, c.port)
        assertEquals(listOf("10.13.13.2/32"), c.localAddresses)
        assertEquals(25, c.wireguardKeepalive)
        assertEquals(listOf("0.0.0.0/0"), c.allowedIps)
        assertEquals("6", c.awg["jc"])
        assertEquals("10", c.awg["jmin"])
        assertEquals("50", c.awg["jmax"])

        assertTrue(c.awg["i1"].startsWith("<r 2><b 0x0102"))
        assertTrue(c.awg["i1"].endsWith("2728>"))
    }

    @Test
    fun `and survives the share link the importer converts it into`() {
        val parsed = ConfigParser.parse(ShareLink.build(ConfigParser.parseWireguardConf(conf)))

        assertEquals("198.51.100.7", parsed.remark)
        assertEquals(25, parsed.wireguardKeepalive)
        assertEquals(listOf("0.0.0.0/0"), parsed.allowedIps)
        assertEquals(ConfigParser.parseWireguardConf(conf).awg.entries, parsed.awg.entries)
    }

    @Test
    fun `the core is told the keepalive and the routes the config asked for`() {
        val json = XrayJsonBuilder.build(ConfigParser.parseWireguardConf(conf))

        assertTrue(json.contains("\"keepAlive\": 25"))
        assertTrue(json.contains("\"0.0.0.0/0\""))

        assertFalse(json.contains("\"::/0\""))
        assertTrue(json.contains("\"endpoint\": \"192.0.2.10:13579\""))
    }

    @Test
    fun `a config that names no routes still gets the full tunnel`() {
        val noRoutes = conf.lines().filterNot { it.startsWith("AllowedIPs") }.joinToString("\n")
        val json = XrayJsonBuilder.build(ConfigParser.parseWireguardConf(noRoutes))

        assertTrue(json.contains("\"0.0.0.0/0\""))
        assertTrue(json.contains("\"::/0\""))
    }
}
