package dev.cluvex.zedsecure.ui.theme

import androidx.compose.ui.graphics.Color
import dev.cluvex.zedsecure.domain.model.AppSettings

data class ThemeProfile(
    val id: String,

    val name: String,

    val accentIndex: Int,
    val amoled: Boolean = false,
    val download: Long,
    val upload: Long,
    val downloadTile: Long,
    val uploadTile: Long,
    val connect: Long,
    val connected: Long,
    val tapHint: Long,
    val serverCard: Long,
    val serverActive: Long,
    val configCard: Long,
    val configCardText: Long,
) {
    val swatches: List<Color>
        get() = listOf(Color(connect), Color(download), Color(upload))
}

val ThemeProfiles: List<ThemeProfile> = listOf(
    ThemeProfile(
        id = "narcis",
        name = "Narcis",
        accentIndex = 0,
        download = 0xFF3FD898,
        upload = 0xFFFFCE54,
        downloadTile = 0xFF0A2E22,
        uploadTile = 0xFF332705,
        connect = 0xFF0F9D6C,
        connected = 0xFF0A6E4E,
        tapHint = 0xFFA5EBCE,
        serverCard = 0xFF0B2A20,
        serverActive = 0xFF0F9D6C,
        configCard = 0xFF0D2F24,
        configCardText = 0xFFE2FFF2,
    ),
    ThemeProfile(
        id = "aurora",
        name = "Aurora",
        accentIndex = 2,
        download = 0xFF4FE3D8,
        upload = 0xFFB49BFF,
        downloadTile = 0xFF0D3B37,
        uploadTile = 0xFF241A48,
        connect = 0xFF12A594,
        connected = 0xFF7C5CFF,
        tapHint = 0xFFA9E9E2,
        serverCard = 0xFF11302E,
        serverActive = 0xFF12A594,
        configCard = 0xFF12332F,
        configCardText = 0xFFEAFFFB,
    ),
    ThemeProfile(
        id = "ember",
        name = "Ember",
        accentIndex = 4,
        download = 0xFFFFB870,
        upload = 0xFFFF8A65,
        downloadTile = 0xFF3D2409,
        uploadTile = 0xFF43200F,
        connect = 0xFFE07A1F,
        connected = 0xFFC0392B,
        tapHint = 0xFFFFD9AE,
        serverCard = 0xFF33200C,
        serverActive = 0xFFE07A1F,
        configCard = 0xFF3A2410,
        configCardText = 0xFFFFF1E2,
    ),
    ThemeProfile(
        id = "midnight",
        name = "Midnight",
        accentIndex = 1,

        amoled = true,
        download = 0xFF7FB2FF,
        upload = 0xFF9BC4FF,
        downloadTile = 0xFF0B1730,
        uploadTile = 0xFF101B36,
        connect = 0xFF2563EB,
        connected = 0xFF1E3A8A,
        tapHint = 0xFFA9C6F5,
        serverCard = 0xFF0C1526,
        serverActive = 0xFF2563EB,
        configCard = 0xFF0D1932,
        configCardText = 0xFFE6EEFF,
    ),
    ThemeProfile(
        id = "sakura",
        name = "Sakura",
        accentIndex = 5,
        download = 0xFFFFA8C5,
        upload = 0xFFFFC2D6,
        downloadTile = 0xFF3E1226,
        uploadTile = 0xFF45182C,
        connect = 0xFFD9407A,
        connected = 0xFF8E2751,
        tapHint = 0xFFFFCFE0,
        serverCard = 0xFF351023,
        serverActive = 0xFFD9407A,
        configCard = 0xFF3B1428,
        configCardText = 0xFFFFF0F5,
    ),
    ThemeProfile(
        id = "citrus",
        name = "Citrus",
        accentIndex = 3,

        download = 0xFFC7F24E,
        upload = 0xFF8FD14F,
        downloadTile = 0xFF243007,
        uploadTile = 0xFF1E2A0A,
        connect = 0xFF9BC91F,
        connected = 0xFF3F6212,
        tapHint = 0xFFDDF59A,
        serverCard = 0xFF1E2708,
        serverActive = 0xFF9BC91F,
        configCard = 0xFF232E09,
        configCardText = 0xFFF2FFD6,
    ),
    ThemeProfile(
        id = "mono",
        name = "Mono",
        accentIndex = 9,
        download = 0xFFE4E4E7,
        upload = 0xFFB4B4BB,
        downloadTile = 0xFF1C1C1E,
        uploadTile = 0xFF232326,
        connect = 0xFF3F3F46,
        connected = 0xFF71717A,
        tapHint = 0xFFC7C7CC,
        serverCard = 0xFF1A1A1C,
        serverActive = 0xFF3F3F46,
        configCard = 0xFF1D1D20,
        configCardText = 0xFFF2F2F7,
    ),
    ThemeProfile(
        id = "neonlime",
        name = "Neon Lime",
        accentIndex = 3,

        amoled = true,
        download = 0xFFD4FF3F,
        upload = 0xFF9EE84A,
        downloadTile = 0xFF0A0F00,
        uploadTile = 0xFF0C1200,
        connect = 0xFFC7F24E,
        connected = 0xFF4A7C0F,
        tapHint = 0xFFDFFF9E,
        serverCard = 0xFF080B00,
        serverActive = 0xFFC7F24E,
        configCard = 0xFF0B1000,
        configCardText = 0xFFEBFFC2,
    ),
    ThemeProfile(
        id = "tokyo",
        name = "Tokyo",
        accentIndex = 1,

        amoled = true,
        download = 0xFF7AA2F7,
        upload = 0xFFBB9AF7,
        downloadTile = 0xFF0B0D17,
        uploadTile = 0xFF11101F,
        connect = 0xFF7AA2F7,
        connected = 0xFFBB9AF7,
        tapHint = 0xFF9AA5CE,
        serverCard = 0xFF090B14,
        serverActive = 0xFF7AA2F7,
        configCard = 0xFF0C0F1A,
        configCardText = 0xFFC0CAF5,
    ),
    ThemeProfile(
        id = "solar",
        name = "Solar",
        accentIndex = 4,

        download = 0xFFFFD54F,
        upload = 0xFFFFB300,
        downloadTile = 0xFF3A2E05,
        uploadTile = 0xFF33280A,
        connect = 0xFFFFC107,
        connected = 0xFF8D6E00,
        tapHint = 0xFFFFE9A8,
        serverCard = 0xFF2E2506,
        serverActive = 0xFFFFC107,
        configCard = 0xFF352A07,
        configCardText = 0xFFFFF6DA,
    ),
    ThemeProfile(
        id = "moss",
        name = "Moss",
        accentIndex = 3,

        download = 0xFF6EE7A8,
        upload = 0xFF34D399,
        downloadTile = 0xFF07231A,
        uploadTile = 0xFF0A2A20,
        connect = 0xFF10B981,
        connected = 0xFF065F46,
        tapHint = 0xFFA7F3D0,
        serverCard = 0xFF061D16,
        serverActive = 0xFF10B981,
        configCard = 0xFF08251C,
        configCardText = 0xFFE3FFF4,
    ),
    ThemeProfile(
        id = "clay",
        name = "Clay",
        accentIndex = 6,

        download = 0xFFE0A08A,
        upload = 0xFFD97757,
        downloadTile = 0xFF33201A,
        uploadTile = 0xFF3A231B,
        connect = 0xFFD97757,
        connected = 0xFF8C4A34,
        tapHint = 0xFFF0C8B6,
        serverCard = 0xFF2B1B15,
        serverActive = 0xFFD97757,
        configCard = 0xFF32201A,
        configCardText = 0xFFFFEDE3,
    ),
)

fun themeProfileOf(id: String?): ThemeProfile? =
    id?.let { wanted -> ThemeProfiles.firstOrNull { it.id == wanted } }

fun AppSettings.applyThemeProfile(profile: ThemeProfile): AppSettings = copy(
    accentColor = profile.accentIndex,

    dynamicColor = false,
    amoledBlack = profile.amoled,
    customDownloadColor = profile.download,
    customUploadColor = profile.upload,
    customDownloadTileColor = profile.downloadTile,
    customUploadTileColor = profile.uploadTile,
    customConnectColor = profile.connect,
    customConnectedColor = profile.connected,
    customTapHintColor = profile.tapHint,
    customServerCardColor = profile.serverCard,
    customServerActiveColor = profile.serverActive,
    customConfigCardColor = profile.configCard,
    customConfigCardTextColor = profile.configCardText,
    themeProfileId = profile.id,
)
